# Generated by Django 3.1.4 on 2021-01-08 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Bags', 'Bags'), ('Shoes', 'Shoes'), ('Tops', 'Tops'), ('Jeans', 'Jeans'), ('Pants', 'Pants'), ('Mobile Phones', 'Mobile Phones'), ('HeadPhones', 'HeadPhones')], default='none', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('header_image', models.ImageField(blank=True, default='/static/blog/product2', null=True, upload_to='images/')),
                ('price', models.CharField(max_length=5)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
